default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: review_apps_development
  host: 127.0.0.1

test:
  <<: *default
  database: review_apps_test
  host: 127.0.0.1

production:
  <<: *default
  database: review_apps_production
  username: review_apps
  password: <%= ENV['REVIEW_APPS_DATABASE_PASSWORD'] || Settings.database&.password %>
